### ISSUE TITLE
Integrate fingerprint and gateway

### ISSUE THREAD

**Issue by rospogrigio** [rospogrigio/airbnk_mqtt#29]
Hi @formatBCE and Merry Xmas!
I need your expertise for something I'd like to accomplish.
I wanted to integrate a fingerprint scanner (specifically the R503, see here: https://esphome.io/components/fingerprint_grow.html) and the BLE gateway within the same ESP32 using ESPHome.
So far I could make it run using the provided example code, but when I tried to introduce the gateway features the firmware fails to compile. In detail, when I add:
```
  includes:
    - airbnk-gateway.h
  libraries:
    - "h2zero/NimBLE-Arduino"
```
I get lots of compilation errors (see next post).
So, here are 2 questions for you:
1) do you think this is feasible, first of all?
2) do you know why I get these compilation errors, and how I can fix these?

Thank you in advance for your support!
rospogrigio

**Comment by rospogrigio** [comment]
...and here are the errors I get when compling:

```
Compiling /data/fingerprint-reader/.pioenvs/fingerprint-reader/lib523/NimBLE-Arduino/NimBLE2904.cpp.o
Compiling /data/fingerprint-reader/.pioenvs/fingerprint-reader/lib523/NimBLE-Arduino/NimBLEAddress.cpp.o
Compiling /data/fingerprint-reader/.pioenvs/fingerprint-reader/lib523/NimBLE-Arduino/NimBLEAdvertisedDevice.cpp.o
Compiling /data/fingerprint-reader/.pioenvs/fingerprint-reader/lib523/NimBLE-Arduino/NimBLEAdvertising.cpp.o
In file included from src/main.cpp:76:
src/airbnk-gateway.h:110:78: error: expected class-name before '{' token
 class AirbnkGatewayNodeComponent : public Component, public CustomMQTTDevice {
                                                                              ^
src/airbnk-gateway.h:152:25: error: 'JsonObject' has not been declared
     void sendBlePayload(JsonObject &root) {
                         ^~~~~~~~~~
src/airbnk-gateway.h:237:21: error: 'JsonObject' has not been declared
     void on_command(JsonObject root) {
                     ^~~~~~~~~~
src/airbnk-gateway.h: In member function 'bool AirbnkGatewayNodeComponent::reportDevice(NimBLEAdvertisedDevice&)':
src/airbnk-gateway.h:125:48: error: 'JsonObject' has not been declared
         publish_json(advert_topic.c_str(), [=](JsonObject root) {
                                                ^~~~~~~~~~
src/airbnk-gateway.h: In lambda function:
src/airbnk-gateway.h:126:27: error: assignment of read-only location '"mac"[root]'
             root["mac"] = mac_address;
                           ^~~~~~~~~~~
src/airbnk-gateway.h:127:28: error: assignment of read-only location '"rssi"[root]'
             root["rssi"] = RSSI;
                            ^~~~
src/airbnk-gateway.h:128:28: error: assignment of read-only location '"data"[root]'
             root["data"] = pHex;
                            ^~~~
src/airbnk-gateway.h: In member function 'bool AirbnkGatewayNodeComponent::reportDevice(NimBLEAdvertisedDevice&)':
src/airbnk-gateway.h:125:9: error: 'publish_json' was not declared in this scope
         publish_json(advert_topic.c_str(), [=](JsonObject root) {
         ^~~~~~~~~~~~
src/airbnk-gateway.h: In member function 'void AirbnkGatewayNodeComponent::sendCommandResult(boolean, std::__cxx11::string, int, std::__cxx11::string)':
src/airbnk-gateway.h:135:17: error: 'is_connected' was not declared in this scope
         while (!is_connected()) { // WiFi most likely was disconnected during command write. Meh.
                 ^~~~~~~~~~~~
src/airbnk-gateway.h:135:17: note: suggested alternative:
In file included from src/esphome.h:25,
                 from src/main.cpp:3:
src/esphome/components/network/util.h:10:6: note:   'esphome::network::is_connected'
 bool is_connected();
      ^~~~~~~~~~~~
In file included from src/main.cpp:76:
src/airbnk-gateway.h:138:56: error: 'JsonObject' has not been declared
         publish_json(command_result_topic.c_str(), [=](JsonObject root) {
                                                        ^~~~~~~~~~
src/airbnk-gateway.h: In lambda function:
src/airbnk-gateway.h:139:31: error: assignment of read-only location '"success"[root]'
             root["success"] = success;
                               ^~~~~~~
src/airbnk-gateway.h:140:41: error: assignment of read-only location '"error"[root]'
             root["error"] = error.c_str();
                                         ^
src/airbnk-gateway.h:141:28: error: assignment of read-only location '"sign"[root]'
             root["sign"] = sign;
                            ^~~~
src/airbnk-gateway.h:142:27: error: assignment of read-only location '"mac"[root]'
             root["mac"] = lock_mac;
                           ^~~~~~~~
src/airbnk-gateway.h:143:47: error: assignment of read-only location '"lockStatus"[root]'
             root["lockStatus"] = status.c_str();
                                               ^
src/airbnk-gateway.h: In member function 'void AirbnkGatewayNodeComponent::sendCommandResult(boolean, std::__cxx11::string, int, std::__cxx11::string)':
src/airbnk-gateway.h:138:9: error: 'publish_json' was not declared in this scope
         publish_json(command_result_topic.c_str(), [=](JsonObject root) {
         ^~~~~~~~~~~~
src/airbnk-gateway.h: In member function 'void AirbnkGatewayNodeComponent::sendBlePayload(int&)':
src/airbnk-gateway.h:163:44: error: invalid conversion from 'char' to 'const char*' [-fpermissive]
         const char* cmnd1 = root["command1"];
                             ~~~~~~~~~~~~~~~^
src/airbnk-gateway.h:164:44: error: invalid conversion from 'char' to 'const char*' [-fpermissive]
         const char* cmnd2 = root["command2"];
                             ~~~~~~~~~~~~~~~^
src/airbnk-gateway.h: In member function 'virtual void AirbnkGatewayNodeComponent::setup()':
src/airbnk-gateway.h:280:9: error: 'subscribe_json' was not declared in this scope
         subscribe_json(command_topic, &AirbnkGatewayNodeComponent::on_command);
         ^~~~~~~~~~~~~~
Compiling /data/fingerprint-reader/.pioenvs/fingerprint-reader/lib523/NimBLE-Arduino/NimBLEBeacon.cpp.o
Compiling /data/fingerprint-reader/.pioenvs/fingerprint-reader/lib523/NimBLE-Arduino/NimBLECharacteristic.cpp.o
Compiling /data/fingerprint-reader/.pioenvs/fingerprint-reader/lib523/NimBLE-Arduino/NimBLEClient.cpp.o
*** [/data/fingerprint-reader/.pioenvs/fingerprint-reader/src/main.cpp.o] Error 1
```

**Comment by rospogrigio** [comment]
FYI, my YAML file is something like this:

```
esphome:
  name: fingerprint-reader
  
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Airbnk-Gateway Fallback Hotspot"
    password: "***HIDDEN***"

ota:
  password: "***HIDDEN***"

captive_portal:

mqtt:
  broker: ***HIDDEN***
  username: !secret mqtt_user # TODO replace with your MQTT user or remove
  password: !secret mqtt_password # TODO replace with your MQTT password or remove
  discovery: false

uart:
  rx_pin: GPIO17
  tx_pin: GPIO22
  baud_rate: 57600

fingerprint_grow:
  sensing_pin: GPIO16
  on_finger_scan_matched:
    - homeassistant.event:
        event: esphome.test_node_finger_scan_matched
        data:
          finger_id: !lambda 'return finger_id;'
          confidence: !lambda 'return confidence;'
  on_finger_scan_unmatched:
    - homeassistant.event:
        event: esphome.test_node_finger_scan_unmatched
  on_enrollment_scan:
    - homeassistant.event:
        event: esphome.test_node_enrollment_scan
        data:
          finger_id: !lambda 'return finger_id;'
          scan_num: !lambda 'return scan_num;'
  on_enrollment_done:
    - homeassistant.event:
        event: esphome.test_node_enrollment_done
        data:
          finger_id: !lambda 'return finger_id;'
  on_enrollment_failed:
    - fingerprint_grow.aura_led_control:
        state: FLASHING
        speed: 25
        color: RED
        count: 4
    - homeassistant.event:
        event: esphome.test_node_enrollment_failed
        data:
          finger_id: !lambda 'return finger_id;'

api:
  encryption:
    key: "lyke/dzMcuKFQiVLM1o8Fjr0AdOCyvqNqLpKJp0sN7k="
  services:
  - service: enroll
    variables:
      finger_id: int
      num_scans: int
    then:
      - fingerprint_grow.enroll:
          finger_id: !lambda 'return finger_id;'
          num_scans: !lambda 'return num_scans;'
  - service: cancel_enroll
    then:
      - fingerprint_grow.cancel_enroll:
 [...]
```
