### ISSUE TITLE
Expose to Google Home/Alexa

### ISSUE THREAD

**Issue by TheDescender** [rospogrigio/airbnk_mqtt#34]
Hey, been a while since I posted here. Does anyone have a good way to expose the lock to Google Home/Alexa. I used to use a cover template for it, but I'm running into issues with reported the state in case of "Operating" and "Failed". I would like to be sure the device status in Google Home/Alexa is accurate, but I'm not sure how to approach this in the yaml config.

So does anyone have a good example of a yaml template button/cover or a suggestion on how to best integrate the lock with Google Home/Alexa.

**Comment by formatBCE** [comment]
I use template lock:

- platform: template
  name: Main door lock
  value_template: "{{ is_state('sensor.lock_status', 'Locked') or is_state('sensor.lock_status', 'Operating') }}"
  availability_template: "{{ not (is_state('sensor.lock_status', 'unavailable')) }}"
  lock:
    service: cover.close_cover
    target:
      entity_id: cover.lock
  unlock:
    service: cover.open_cover
    target:
      entity_id: cover.lock

Then expose that one. Also better for dashboard displaying :)

**Comment by formatBCE** [comment]
I use template lock:

- platform: template
  name: Main door lock
  value_template: "{{ is_state('sensor.lock_status', 'Locked') or is_state('sensor.lock_status', 'Operating') }}"
  availability_template: "{{ not (is_state('sensor.lock_status', 'unavailable')) }}"
  lock:
    service: cover.close_cover
    target:
      entity_id: cover.lock
  unlock:
    service: cover.open_cover
    target:
      entity_id: cover.lock

Then expose that one. Also better for dashboard displaying :)

P.S. sorry for lack of markdown - phone app for GitHub seems limited.

**Comment by TheDescender** [comment]
Yeah i'm currently using my own version of that. Still uses the old template yaml format. 
```
- platform: template
    covers:
      template_front_door:
        device_class: shade
        friendly_name: "Front Door"
        open_cover:
          service: cover.open_cover
          data:
            entity_id: cover.front_door
        close_cover:
          service: cover.close_cover
          data:
            entity_id: cover.front_door
        value_template: >-
          {% if is_state('sensor.front_door_status', 'Locked') %}
            closed
          {% elif is_state('cover.ben_s_blind', 'Unlocked') %}
            open
          {% elif is_state('cover.ben_s_blind', 'Operating') %}
            opening
          {% else %}
            open
          {% endif %}
        icon_template: >-
          {% if state_attr('cover.front_door', 'icon') | string == 'hass:lock-reset' %} 
            mdi:lock-reset
          {% elif state_attr('cover.front_door', 'icon') | string == 'hass:lock-question' %} 
            mdi:lock-question
          {% elif state_attr('cover.front_door', 'icon') | string == 'hass:lock-alert' %} 
            mdi:lock-alert
          {% elif is_state('sensor.front_door_status', 'Locked') %}
            mdi:door-closed
          {% elif is_state('sensor.front_door_status', 'Unlocked') %}
            mdi:door-closed-lock
          {% endif %}
```
Besides the different approach to value_template, the main difference between our 2 templates is your use of: 
`"availability_template: "{{ not (is_state('sensor.lock_status', 'unavailable')) }}"`
I haven't touched templates since they changed the format. Does availability_template parameter account for the failure to connect through Google Home when sensor.lock_status is on "Failed" or "Operating"? 

Because with my old solution, if I assign the template entity state based on the lock sensor it'll set the state to "unknown" which makes the device unavailable in Ghome.

Using your format I'd likely end up with the following, does that seem right?
```
  - platform: template
    covers:
      template_front:
        friendly_name: Front Door Lock
        value_template: "{{ is_state('sensor.front_door_status', 'Locked') or is_state('sensor.front_door_status', 'Operating') }}"
        availability_template: "{{ not (is_state('sensor.front_door_status', 'unavailable')) }}"
        open_cover:
          service: cover.close_cover
          target:
            entity_id: cover.front_door
        close_cover:
          service: cover.open_cover
          target:
            entity_id: cover.front_door
```
